=== badqiu/rapid-framework/trunk/rapid-framework/generator/src_ext/cn/org/rapid_framework/generator/ext/tableconfig/rapid-ibatis-table-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT table (column* | resultmap* | operation* | sql*)+>
<!ATTLIST table
namespace CDATA #IMPLIED
remarks CDATA #IMPLIED
sqlname CDATA #IMPLIED
dummypk CDATA #IMPLIED
package CDATA #IMPLIED
subpackage CDATA #IMPLIED
sequence CDATA #IMPLIED
autoswitchdatasrc CDATA #IMPLIED
doname CDATA #IMPLIED
>

<!ELEMENT column EMPTY>
<!ATTLIST column
name CDATA #REQUIRED
javatype CDATA #REQUIRED
>

<!ELEMENT resultmap (column)*>
<!ATTLIST resultmap
name CDATA #REQUIRED
>

<!ELEMENT operation (extraparams | sql | sqlmap)*>
<!ATTLIST operation
name CDATA #REQUIRED
paging CDATA #IMPLIED
paramtype CDATA #IMPLIED
multiplicity (one|many|paging) #IMPLIED
remarks CDATA #IMPLIED
>

<!ELEMENT extraparams (param)*>

<!ELEMENT param EMPTY>
<!ATTLIST param
name CDATA #REQUIRED
javatype CDATA #REQUIRED
>

<!ELEMENT sql (#PCDATA | selectKey | include | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST sql
id CDATA #IMPLIED
>

<!ELEMENT sqlmap (#PCDATA | selectKey | include | dynamic | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>

<!--The <include> tag can be used to insert SQL code fragments defined by the <sql> tag into
a SQL statement. Here is a short example:
<br>
Example:<br>
&lt;sql id="selectItem_fragment"&gt;<br>
	FROM items<br>
	WHERE parentid = 6<br>
&lt;/sql&gt;<br>

&lt;select id="selectItemCount" resultClass="int"&gt;<br>
	SELECT COUNT(*) AS total<br>
	<include refid="selectItem_fragment"/><br>
&lt;/select&gt;<br>

&lt;select id="selectItems" resultClass="Item"&gt;<br>
	SELECT id, name<br>
	&lt;include refid="selectItem_fragment"/><br>
&lt;/select&gt;-->
<!ELEMENT include EMPTY>
<!ATTLIST include
refid CDATA #REQUIRED
>

<!--Many relational database systems support auto-generation of primary key fields. This feature of the
RDBMS is often (if not always) proprietary. Data Mapper supports auto-generated keys via the
<selectKey> stanza of the <insert> element. Both pre-generated keys (e.g. Oracle) and post-generated
(MS-SQL Server) keys are supported.
The selectKey statement is executed before the insert statement if it is placed before the insert SQL,
otherwise the selectKey statement is executed after the insert statement. In the previous examples, the
Oracle example shows that the selectKey will be executed before the insert statement (as is appropriate for
a sequence). The SQL Server example shows that the selectKey statement will be executed after the insert
statement (as is appropriate for an identity column).
With iBATIS versions 2.2.0 and later, you can explicitly state the order of execution of the statements if
you wish. The selectKey element supports an attribute type that can be used to explicitly set the execution
order. The value of the type attribute can be either “pre” or “post” - meaning that the statement will be
executed before or after the insert statement. If you specify the type attribute, then the value you specify
will be used regardless of the position of the selectKey element.-->
<!ELEMENT selectKey (#PCDATA | include)*>
<!ATTLIST selectKey
resultClass CDATA #IMPLIED
keyProperty CDATA #IMPLIED
type (pre|post) #IMPLIED
>

<!-- - - - - - - - - - - - - - - - - - - - - - - - -
                 DYNAMIC ELEMENTS
  - - - - - - - - - - - - - - - - - - - - - - - - -->

<!--Wrapper tag that allows for an overall prepend, open and close.-->
<!ELEMENT dynamic (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST dynamic
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
>

<!--Checks if a property is not null.-->
<!ELEMENT isNotNull (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNotNull
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
>

<!--Checks if a property is null.-->
<!ELEMENT isNull (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNull
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
>

<!--Checks if a property is unavailable (i.e not a property of the parameter bean).-->
<!ELEMENT isNotPropertyAvailable (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNotPropertyAvailable
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #REQUIRED
removeFirstPrepend (true|false) #IMPLIED
>

<!--Checks if a property is available (i.e is a property of the parameter bean).-->
<!ELEMENT isPropertyAvailable (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isPropertyAvailable
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #REQUIRED
removeFirstPrepend (true|false) #IMPLIED
>

<!--Checks the equality of a property and a value, or another property.-->
<!ELEMENT isEqual (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isEqual
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!--Checks the inequality of a property and a value, or another property.-->
<!ELEMENT isNotEqual (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNotEqual
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!--Checks if a property is greater than a value or another property.-->
<!ELEMENT isGreaterThan (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isGreaterThan
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!--Checks if a property is greater than or equal to a value or another property.-->
<!ELEMENT isGreaterEqual (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isGreaterEqual
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!--Checks if a property is less than a value or another property.-->
<!ELEMENT isLessThan (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isLessThan
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!--Checks if a property is less than or equal to a value or another property.
<br>
Example Usage:<br>
&lt;isLessEqual prepend=”AND” property=”age” compareValue=”18”&gt;<br>
	ADOLESCENT = ‘TRUE’<br>
&lt;/isLessEqual&gt;-->
<!ELEMENT isLessEqual (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isLessEqual
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
compareProperty CDATA #IMPLIED
compareValue CDATA #IMPLIED
>

<!--Checks to see if the value of a Collection, String or String.valueOf() property
is null or empty (“” or size() < 1).-->
<!ELEMENT isEmpty (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isEmpty
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
>

<!--Checks to see if the value of a Collection, String or String.valueOf() property
is not null and not empty (“” or size() < 1).
<br><br>
Example Usage:<br>
&lt;isNotEmpty prepend=”AND” property=”firstName” &gt;<br>
	FIRST_NAME=#firstName#<br>
&lt;/isNotEmpty&gt;-->
<!ELEMENT isNotEmpty (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNotEmpty
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
>

<!--Checks to see if the parameter object is present (not null).-->
<!ELEMENT isParameterPresent (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isParameterPresent
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
>

<!--Checks to see if the parameter object is not present (null). -->
<!ELEMENT isNotParameterPresent (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST isNotParameterPresent
prepend CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
removeFirstPrepend (true|false) #IMPLIED
>

<!--Iterates over a property that is an implementation java.util.Collection, or
java.util.Iterator, or is an array.
<br><br>
Example Usage:<br>
&lt;iterate prepend=”AND” property=”userNameList” open=”(” close=”)” conjunction=”OR”&gt;<br>
	username=#userNameList[]#<br>
&lt;/iterate&gt;<br>
<br>
It is also possible to use the iterate when the collection is passed in as a
parameter to your mapped statement.
<br>
Example Usage:<br>
&lt;iterate prepend=”AND” open=”(” close=”)” conjunction=”OR”&gt;<br>
	username=#[]#<br>
&lt;/iterate&gt;<br>

Note: It is very important to include the square brackets[] at the end of the
property name when using the Iterate element. These brackets distinguish this
object as a collection to keep the parser from simply outputting the collection
as a string.-->
<!ELEMENT iterate (#PCDATA | include | iterate | isParameterPresent | isNotParameterPresent | isEmpty | isNotEmpty | isNotNull | isNull | isNotEqual | isEqual | isGreaterThan | isGreaterEqual | isLessThan | isLessEqual | isPropertyAvailable | isNotPropertyAvailable)*>
<!ATTLIST iterate
prepend CDATA #IMPLIED
property CDATA #IMPLIED
removeFirstPrepend (true|false|iterate) #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
conjunction CDATA #IMPLIED
>

=== badqiu/rapid-framework/trunk/rapid-framework/generator/src_ext/cn/org/rapid_framework/generator/ext/tableconfig/dtd_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "rapid-ibatis-table-config.dtd">

<!-- 
<!DOCTYPE table PUBLIC "-//www.rapid-framework.org.cn//DTD Table Config 2.0//CN" 
    "rapid-ibatis-table-config.dtd">
 -->
<table dummypk="" namespace="" remarks="" sequence="" sqlname="">

	<column name="service_fee" javatype="com.iwallet.biz.common.util.money.Money" />
	<column name="SERVICE_FEE" javatype="com.iwallet.biz.common.util.money.Money" />
	
	<column name="TOTAL_FEE" javatype="com.iwallet.biz.common.util.money.Money" />
	<column name="SERVICE_FEE_RATIO" javatype="double" />
	<column javatype="" name=""/>
	<column name="amount" javatype="com.iwallet.biz.common.util.money.Money" />
	<column name="AMOUNT" javatype="com.iwallet.biz.common.util.money.Money" />
	
	<column name="bank_amount" javatype="com.iwallet.biz.common.util.money.Money" />
	<column name="BANK_AMOUNT" javatype="com.iwallet.biz.common.util.money.Money" />
	
	<column name="return_fee" javatype="com.iwallet.biz.common.util.money.Money" />
	<column name="RETURN_FEE" javatype="com.iwallet.biz.common.util.money.Money" />
	
	<column javatype="" name=""/>
	
	<resultmap name="">
		<column javatype="" name=""/>
	</resultmap>
	
	<operation name="" multiplicity="one" paramtype="" remarks="">
		<sql>
		</sql>
		<sqlmap>
		
		</sqlmap>
	</operation>
	
	<sql id="findAccountLog.where">
		<isNotEmpty >
		
		</isNotEmpty>
		<isGreaterEqual>
			
		</isGreaterEqual>
		<iterate open="" close=""></iterate>
	  	<isEmpty property="accountNo">
			<isEmpty property="transDtBegin">
		  		<isEmpty property="transDtEnd">
		        	query not allowed
		  		</isEmpty>
			</isEmpty>
  	  	</isEmpty>
				
    	<isEqual prepend="and" property="isIncomeOrOutcome" compareValue="INCOME">
			MAL.TRANS_AMOUNT > 0
		</isEqual> 
		
    	<isEqual prepend="and" property="isIncomeOrOutcome" compareValue="OUTCOME">
			MAL.TRANS_AMOUNT &lt; 0
		</isEqual>
				
    	<isNotEmpty prepend="and" property="iwAccountLogId">
			MAL.IW_ACCOUNT_LOG_ID = #iwAccountLogId#
		</isNotEmpty> 
	</sql>
	
	<operation name="findAccountLogWithAirExt" paging="true" paramtype="primitive" remarks="帐务明细查询">
		<extraparams>
			<param name="isIncomeOrOutcome" javatype="java.lang.String"/>
			<param name="payType" javatype="java.lang.String"/>	
			<param name="minTransAmount" javatype="Long"/>	
			<param name="maxTransAmount" javatype="Long"/>	
		</extraparams>	
		<sql>
			<include refid=""/>
			<iterate></iterate>
		</sql>
		<sqlmap>
		</sqlmap>
	</operation>
	
</table>

=== badqiu/rapid-framework/trunk/rapid-framework/generator/src_ext/cn/org/rapid_framework/generator/ext/ibatis/system_partner_query_trade_base.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "rapid-ibatis-table-config.dtd">

<table sqlname="trade_base"  remarks="交易信息表" doname="AirTradeBase">

	<column name="TOTAL_FEE" javatype="com.iwallet.biz.common.util.money.Money" />
	<column name="SERVICE_FEE" javatype="com.iwallet.biz.common.util.money.Money" />
	<column name="SERVICE_FEE_RATIO" javatype="double" />
	
	<column name="buyer_type" javatype="int" />
	<column name="seller_type" javatype="int" />
	<column name="id" javatype="long" />
	    
    <sql id="findTradeBySystemParnter.where">
    		<isNotEmpty prepend="and" property="gmtCreateBeing">
    		BTB.gmt_create >= #gmtCreateBeing#
    		</isNotEmpty>
    		
    		<isNotEmpty prepend="and" property="gmtCreateEnd">
    		BTB.gmt_create &lt; #gmtCreateEnd#
    		</isNotEmpty>
    		
    		<isNotEmpty prepend="and" property="gmtPayBegin">
    		BTF.gmt_pay >= #gmtPayBegin# 
    		</isNotEmpty>
    		
    		<isNotEmpty prepend="and" property="gmtPayEnd">
    		BTF.gmt_pay  &lt; #gmtPayEnd# 
    		</isNotEmpty>
			
			<isNotEmpty prepend="and" property="tradeNo">
				BTB.trade_no = #tradeNo#
			</isNotEmpty>

			<isNotEmpty prepend="and" property="buyyerLoginEmail">
				BTB.buyer_login_email = ?
			</isNotEmpty>

			<isNotEmpty prepend="and" property="sellerLoginEmail">
				BTB.seller_login_email = ?
			</isNotEmpty>
									
			<isNotEmpty prepend="and" property="outTradeNo">
				BTB.out_trade_no = #outTradeNo#
			</isNotEmpty>
			
			<isNotEmpty prepend="and" property="tradeTypes">
				BTB.trade_type IN
				<iterate property="tradeTypes" open="(" close=")" conjunction=",">
					#tradeTypes[]#
				</iterate>
			</isNotEmpty>
			
			<isNotEmpty prepend="and" property="tradeStatuses">
				 BTB.trade_status IN
				<iterate property="tradeStatuses" open="(" close=")" conjunction=",">
					#tradeStatuses[]#
				</iterate>
			</isNotEmpty>
			
			<isNotEmpty prepend="and" property="notInTradeStatuses">
				 BTB.trade_status NOT IN
				<iterate property="notInTradeStatuses" open="(" close=")" conjunction=",">
					#notInTradeStatuses[]#
				</iterate>
			</isNotEmpty>
			
			<isNotEmpty prepend="and" property="goodsTitle">
				BTB.goods_title LIKE #goodsTitle# 
			</isNotEmpty>

			<isNotEmpty prepend="and" property="tradePriceDown">
					BTB.total_fee &gt;= #tradePriceDown#
			</isNotEmpty>
			<isNotEmpty prepend="and" property="tradePriceUp">
					BTB.total_fee &lt;= #tradePriceUp#
			</isNotEmpty>

			<isNotEmpty prepend="and" property="includeSystemPartners">
					system_partner in <iterate property="includeSystemPartners" open="(" close=")" conjunction=",">#includeSystemPartners[]#</iterate> 
			</isNotEmpty>
			<isNotEmpty prepend="and" property="excludeSystemPartners">
					system_partner not in <iterate property="excludeSystemPartners" open="(" close=")" conjunction=",">#excludeSystemPartners[]#</iterate> 
			</isNotEmpty>
    </sql>
    
    <operation name="findTradeBySystemParnter" paramtype="primitive" multiplicity="paging" remarks="系统平台商交易查询">
    	<sql>
    		SELECT 
    		BTB.id,BTB.trade_no,out_trade_no,seller_account,seller_login_email,buyer_account,buyer_login_email,seller_type,buyer_type,trade_from,trade_email,operator_role,trade_status,total_fee,service_fee_ratio,service_fee,BTB.currency,seller_action,buyer_action,BTB.gmt_create,seller_user_id,buyer_user_id,additional_trd_status,trade_type,seller_fullname,buyer_fullname,seller_nick,buyer_nick,goods_title,gmt_last_modified_dt,stop_timeout,gathering_type,buyer_marker,seller_marker,buyer_marker_memo,seller_marker_memo,BTB.channel,product,pay_channel,
    		PNR,MAE.TICKET_NO_START,MAE.TICKET_NO_END,MAE.system_partner,
    		BTF.gmt_pay,
    			        
    		(case
	        when (BTB.channel = '70' ) then 'CREDIT_PAY'
	        else
	        	'BALANCE_PAY'
	        end) as systemPartnerPayType
	        	        
    		FROM trade_base BTB 
				left join mcenter_air_ext MAE on 
					BTB.trade_no = MAE.trade_no and BTB.owner = MAE.owner
    			left join trade_fund_bill BTF on 
    				BTB.trade_no = BTF.trade_no and BTB.owner = BTF.owner and BTF.type = '10'
    		WHERE BTB.owner IN <iterate property="owner" open="(" close=")" conjunction=",">#owner[]#</iterate> 
    		
			<include refid="findTradeBySystemParnter.where"/>
			
			<isNotEmpty prepend="and" property="gmtPayBegin">
			order by BTF.gmt_pay desc
			</isNotEmpty>
			<isEmpty prepend="and" property="gmtPayBegin">
			order by BTB.gmt_create desc
			</isEmpty>
		</sql>
    </operation>


    	         			
</table>

=== badqiu/rapid-framework/trunk/rapid-framework/generator/src_ext/cn/org/rapid_framework/generator/ext/tableconfig/system_partner_query_trade_base.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "rapid-ibatis-table-config.dtd">

<table sqlname="trade_base"  remarks="交易信息表" doname="AirTradeBase">

	<column name="TOTAL_FEE" javatype="com.iwallet.biz.common.util.money.Money" />
	<column name="SERVICE_FEE" javatype="com.iwallet.biz.common.util.money.Money" />
	<column name="SERVICE_FEE_RATIO" javatype="double" />
	
	<column name="buyer_type" javatype="int" />
	<column name="seller_type" javatype="int" />
	<column name="id" javatype="long" />
	    
    <sql id="findTradeBySystemParnter.where">
    		
    		<isEqual property="systemPartnerTradeStatus" compareValue="WAIT_PAY" >
    			and BTB.trade_status in ('WAIT_BUYER_PAY','TRADE_CLOSED') and BTF.trade_no is null
    		</isEqual>
    		<isEqual property="systemPartnerTradeStatus" compareValue="PAID" >
    			and BTF.type = '01'
    		</isEqual>
    		    		
    		<isNotEmpty prepend="and" property="gmtPayBegin">
    		BTF.gmt_pay >= #gmtPayBegin# 
    		</isNotEmpty>
    		
    		<isNotEmpty prepend="and" property="gmtPayEnd">
    		BTF.gmt_pay  &lt; #gmtPayEnd# 
    		</isNotEmpty>
    		    
    		<isNotEmpty prepend="and" property="gmtCreateBeing">
    		BTB.gmt_create >= #gmtCreateBeing#
    		</isNotEmpty>
    		
    		<isNotEmpty prepend="and" property="gmtCreateEnd">
    		BTB.gmt_create &lt; #gmtCreateEnd#
    		</isNotEmpty>
    		
			<isNotEmpty prepend="and" property="tradeNo">
				BTB.trade_no = #tradeNo#
			</isNotEmpty>

			<isNotEmpty prepend="and" property="buyerLoginEmail">
				BTB.buyer_login_email = #buyerLoginEmail#
			</isNotEmpty>

			<isNotEmpty prepend="and" property="sellerLoginEmail">
				BTB.seller_login_email = #sellerLoginEmail#
			</isNotEmpty>
									
			<isNotEmpty prepend="and" property="outTradeNo">
				BTB.out_trade_no = #outTradeNo#
			</isNotEmpty>

			<isNotEmpty prepend="and" property="tradeEmail">
				BTB.trade_email = #tradeEmail#
			</isNotEmpty>			
			
			<isNotEmpty prepend="and" property="tradeTypes">
				BTB.trade_type IN
				<iterate property="tradeTypes" open="(" close=")" conjunction=",">
					#tradeTypes[]#
				</iterate>
			</isNotEmpty>
			
			<isNotEmpty prepend="and" property="tradeStatuses">
				 BTB.trade_status IN
				<iterate property="tradeStatuses" open="(" close=")" conjunction=",">
					#tradeStatuses[]#
				</iterate>
			</isNotEmpty>
			
			<isNotEmpty prepend="and" property="notInTradeStatuses">
				 BTB.trade_status NOT IN
				<iterate property="notInTradeStatuses" open="(" close=")" conjunction=",">
					#notInTradeStatuses[]#
				</iterate>
			</isNotEmpty>
			
			<isNotEmpty prepend="and" property="goodsTitle">
				BTB.goods_title LIKE #goodsTitle# 
			</isNotEmpty>

			<isNotEmpty prepend="and" property="includeSystemPartners">
					MAE.system_partner in <iterate property="includeSystemPartners" open="(" close=")" conjunction=",">#includeSystemPartners[]#</iterate> 
			</isNotEmpty>
			<isNotEmpty prepend="and" property="excludeSystemPartners">
					MAE.system_partner not in <iterate property="excludeSystemPartners" open="(" close=")" conjunction=",">#excludeSystemPartners[]#</iterate> 
			</isNotEmpty>
    </sql>
    
    <sql id="findTradeBySystemParnter.columns">
    		BTB.id,BTB.trade_no,out_trade_no,seller_account,seller_login_email,buyer_account,buyer_login_email,seller_type,buyer_type,trade_from,trade_email,operator_role,trade_status,total_fee,service_fee_ratio,service_fee,BTB.currency,seller_action,buyer_action,BTB.gmt_create,seller_user_id,buyer_user_id,additional_trd_status,trade_type,seller_fullname,buyer_fullname,seller_nick,buyer_nick,goods_title,gmt_last_modified_dt,stop_timeout,gathering_type,buyer_marker,seller_marker,buyer_marker_memo,seller_marker_memo,BTB.channel,product,pay_channel,
    		PNR,MAE.TICKET_NO_START,MAE.TICKET_NO_END,MAE.system_partner,
    		BTF.gmt_pay,
    			        
    		(case
	        when (BTF.channel = '70' ) then 'CREDIT_PAY'
	        when (BTF.channel is null ) then null
	        else
	        	'BALANCE_PAY'
	        end) as systemPartnerPayType
    </sql>
    
    <operation name="findTradeBySystemParnterWithTradeBase" paramtype="primitive" multiplicity="paging" remarks="系统平台商交易查询(按创建时间查)">
    	<extraparams>
    		<param javatype="String" name="systemPartnerTradeStatus"/>
    	</extraparams>    
    	<sql>
    		SELECT 
			<include refid="findTradeBySystemParnter.columns"/>
    		FROM trade_base BTB 
				left join mcenter_air_ext MAE on 
					BTB.trade_no = MAE.trade_no and BTB.owner = MAE.owner
    			left join trade_fund_bill BTF on 
    				BTB.trade_no = BTF.trade_no and BTB.owner = BTF.owner and BTF.type = '01'
    		WHERE BTB.owner IN <iterate property="owner" open="(" close=")" conjunction=",">#owner[]#</iterate> 
    		
			<include refid="findTradeBySystemParnter.where"/>
			
			<isNotEmpty property="gmtPayBegin">
			order by BTF.gmt_pay desc
			</isNotEmpty>
			<isEmpty property="gmtPayBegin">
			order by BTB.gmt_create desc
			</isEmpty>
		</sql>
    </operation>

    <operation name="findTradeBySystemParnterWithTradeFundBill" paramtype="primitive" multiplicity="paging" remarks="系统平台商交易查询(按支付时间查)">
    	<extraparams>
    		<param javatype="String" name="systemPartnerTradeStatus"/>
    	</extraparams>
    	<sql>
    		SELECT 
			<include refid="findTradeBySystemParnter.columns"/>
    		FROM trade_base BTB 
				left join mcenter_air_ext MAE on 
					BTB.trade_no = MAE.trade_no and BTB.owner = MAE.owner
    			inner join trade_fund_bill BTF on 
    				BTB.trade_no = BTF.trade_no and BTB.owner = BTF.owner and BTF.type = '01'
    		WHERE BTB.owner IN <iterate property="owner" open="(" close=")" conjunction=",">#owner[]#</iterate> 
    		
			<include refid="findTradeBySystemParnter.where"/>
			
			<isNotEmpty property="gmtPayBegin">
			order by BTF.gmt_pay desc
			</isNotEmpty>
			<isEmpty property="gmtPayBegin">
			order by BTB.gmt_create desc
			</isEmpty>
		</sql>
    </operation>
    	         			
</table>
