=== badqiu/rapid-framework/trunk/dtd/groups.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT groups ( comment?,group* ) >
<!ELEMENT comment (#PCDATA) >
<!ELEMENT group ( property* ) >
<!ELEMENT property (#PCDATA) >
<!ATTLIST property key CDATA #REQUIRED>
<!ATTLIST group name CDATA #REQUIRED>

=== badqiu/rapid-framework/trunk/rapid-framework/java_src_sandbox/cn/org/rapid_framework/config/group/groups_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE groups SYSTEM "http://rapid-framework.googlecode.com/svn/trunk/dtd/groups.dtd">
<groups>

	<comment></comment>
	
	<group name="g1">
		<property key="g1_1">v1_1</property>
		<property key="g1_2">v1_2</property>
		<property key="1">v1</property>
	</group>
	
	<group name="g2">
		<property key="g2_1">v2_1</property>
		<property key="g2_2">v2_2</property>
		<property key="1">v1</property>
	</group>	
	
</groups>

=== badqiu/rapid-framework/trunk/rapid-framework/java_src_sandbox/cn/org/rapid_framework/util/config/group/groups_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE groups SYSTEM "http://rapid-framework.googlecode.com/svn/trunk/dtd/groups.dtd">
<groups>

	<comment>12123</comment>
	
	<group name="findByPage">
		<property name="g1_1">v1_1</property>
		<property name="g1_2">v1_2</property>
		<property name="1">v1</property>
	</group>

	<group name="UserInfo">
		<property name="deleteBySql">
			select * from user where username = :username
		</property>
		<property name="insertBySql">
			select * from blog where age = :age
		</property>
		<property name="update">
			select * from blog where hibernate=:hibernate
		</property>
	</group>	
	
</groups>

=== badqiu/rapid-framework/tags/rapid-framework/3.6.0-preview/java_src_sandbox/cn/org/rapid_framework/util/config/group/groups_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE groups SYSTEM "http://rapid-framework.googlecode.com/svn/trunk/dtd/groups.dtd">
<groups>

	<comment>12123</comment>
	
	<group name="g1">
		<property name="g1_1">v1_1</property>
		<property name="g1_2">v1_2</property>
		<property name="1">v1</property>
	</group>

	<group name="g2">
		<property name="g2_1">v2_1</property>
		<property name="g2_2">v2_2</property>
		<property name="1">v1</property>
	</group>	
	
</groups>
