=== badqiu/rapid-framework/tags/parent-4.0.3/rapid-generator/rapid-generator-ext/src/test/resources/cn/org/rapid_framework/generator/ext/tableconfig/rapid-mybatis-table-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT table (column* | resultmap* | operation* | sql*)+>
<!ATTLIST table
namespace CDATA #IMPLIED
remarks CDATA #IMPLIED
sqlname CDATA #IMPLIED
dummypk CDATA #IMPLIED
package CDATA #IMPLIED
subpackage CDATA #IMPLIED
sequence CDATA #IMPLIED
autoswitchdatasrc CDATA #IMPLIED
doname CDATA #IMPLIED
>

<!ELEMENT column EMPTY>
<!ATTLIST column
name CDATA #REQUIRED
javatype CDATA #REQUIRED
>

<!ELEMENT resultmap (column)*>
<!ATTLIST resultmap
name CDATA #REQUIRED
>

<!ELEMENT operation (extraparams | sql | sqlmap)*>
<!ATTLIST operation
name CDATA #REQUIRED
paging CDATA #IMPLIED
paramtype CDATA #IMPLIED
multiplicity (one|many|paging) #IMPLIED
remarks CDATA #IMPLIED
>

<!ELEMENT extraparams (param)*>

<!ELEMENT param EMPTY>
<!ATTLIST param
name CDATA #REQUIRED
javatype CDATA #REQUIRED
>

<!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST sql
id CDATA #IMPLIED
>

<!ELEMENT sqlmap (#PCDATA | include | trim | where | set | foreach | choose | if)*>

<!--The <include> tag can be used to insert SQL code fragments defined by the <sql> tag into
a SQL statement. Here is a short example:
<br>
Example:<br>
&lt;sql id="selectItem_fragment"&gt;<br>
	FROM items<br>
	WHERE parentid = 6<br>
&lt;/sql&gt;<br>

&lt;select id="selectItemCount" resultClass="int"&gt;<br>
	SELECT COUNT(*) AS total<br>
	<include refid="selectItem_fragment"/><br>
&lt;/select&gt;<br>

&lt;select id="selectItems" resultClass="Item"&gt;<br>
	SELECT id, name<br>
	&lt;include refid="selectItem_fragment"/><br>
&lt;/select&gt;-->
<!ELEMENT include EMPTY>
<!ATTLIST include
refid CDATA #REQUIRED
>

<!--Many relational database systems support auto-generation of primary key fields. This feature of the
RDBMS is often (if not always) proprietary. Data Mapper supports auto-generated keys via the
<selectKey> stanza of the <insert> element. Both pre-generated keys (e.g. Oracle) and post-generated
(MS-SQL Server) keys are supported.
The selectKey statement is executed before the insert statement if it is placed before the insert SQL,
otherwise the selectKey statement is executed after the insert statement. In the previous examples, the
Oracle example shows that the selectKey will be executed before the insert statement (as is appropriate for
a sequence). The SQL Server example shows that the selectKey statement will be executed after the insert
statement (as is appropriate for an identity column).
With iBATIS versions 2.2.0 and later, you can explicitly state the order of execution of the statements if
you wish. The selectKey element supports an attribute type that can be used to explicitly set the execution
order. The value of the type attribute can be either “pre” or “post” - meaning that the statement will be
executed before or after the insert statement. If you specify the type attribute, then the value you specify
will be used regardless of the position of the selectKey element.-->
<!ELEMENT selectKey (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST selectKey
resultType CDATA #IMPLIED
statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
keyProperty CDATA #IMPLIED
order (BEFORE|AFTER) #IMPLIED
>

<!-- - - - - - - - - - - - - - - - - - - - - - - - -
                 DYNAMIC ELEMENTS
  - - - - - - - - - - - - - - - - - - - - - - - - -->

<!-- Dynamic -->

<!ELEMENT include EMPTY>
<!ATTLIST include
refid CDATA #REQUIRED
>

<!ELEMENT sql (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST sql
id CDATA #REQUIRED
>

<!ELEMENT trim (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST trim
prefix CDATA #IMPLIED
prefixOverrides CDATA #IMPLIED
suffix CDATA #IMPLIED
suffixOverrides CDATA #IMPLIED
>
<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST foreach
collection CDATA #REQUIRED
item CDATA #IMPLIED
index CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
separator CDATA #IMPLIED
>

<!ELEMENT choose (when* , otherwise?)>
<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST when
test CDATA #REQUIRED
>
<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST if
test CDATA #REQUIRED
>

=== badqiu/rapid-framework/trunk/rapid-mvn/rapid-generator/rapid-generator-ext/src/test/resources/cn/org/rapid_framework/generator/ext/tableconfig/mybatis_user_info.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table SYSTEM "rapid-mybatis-table-config.dtd">
<table sqlname="user_info" doname="MyBatisUserInfo" dummypk="user_id" sequence="SEQ_BBCC_CUSTOMER" subpackage="mybatis_subpackage" package="com.qq" autoswitchdatasrc="false" remarks="用户信息表">
	
	<!-- 用于select查询公用抽取的列 -->
	<sql id="UserInfo.columns">
	    <![CDATA[
		USER_ID,USERNAME,PASSWORD,BIRTH_DATE,SEX,AGE
	    ]]>
	</sql>

	<!-- useGeneratedKeys="true" keyProperty="xxx" for sqlserver and mysql  useGeneratedKeys="true" keyProperty="userId"-->
	<operation name="UserInfo.insert" >
	<sql>
    <![CDATA[
        INSERT INTO USER_INFO (
        	USER_ID ,
        	USERNAME ,
        	PASSWORD ,
        	BIRTH_DATE ,
        	SEX ,
        	AGE 
        ) VALUES (
        	#{userId} ,
        	#{username} ,
        	#{password} ,
        	#{birthDate} ,
        	#{sex} ,
        	#{age} 
        )
    ]]>
	</sql>
	</operation>
    
	<operation name="UserInfo.update" >
	<sql>
    <![CDATA[
        UPDATE USER_INFO SET
	        USERNAME = #{username} ,
	        PASSWORD = #{password} ,
	        BIRTH_DATE = #{birthDate} ,
	        SEX = #{sex} ,
	        AGE = #{age} 
        WHERE 
	        USER_ID = #{userId} 
    ]]>
	</sql>
	</operation>

    <operation name="UserInfo.delete">
    <sql>
    <![CDATA[
        DELETE FROM USER_INFO WHERE
        USER_ID = #{id} 
    ]]>
    </sql>
    </operation>
    
    <!-- resultMap="RM.UserInfo" -->
    <operation name="UserInfo.getById" >
    <sql>
		SELECT <include refid="UserInfo.columns" />
	    <![CDATA[
		    FROM USER_INFO 
	        WHERE 
		        USER_ID = #{id} 
	    ]]>
	</sql>
	</operation>
	
	<sql id="UserInfo.findPage.where">
		<!-- ognl访问静态方法的表达式 为@class@method(args),以下为调用rapid中的Ognl.isNotEmpty()方法,还有其它方法如isNotBlank()可以使用，具体请查看Ognl类 -->
		<where>	      				
	       <if test="@Ognl@isNotEmpty(userId)">
				AND USER_ID = #{userId}
			</if>
	       <if test="@Ognl@isNotEmpty(username)">
				AND USERNAME = #{username}
			</if>
	       <if test="@Ognl@isNotEmpty(password)">
				AND PASSWORD = #{password}
			</if>
	       <if test="@Ognl@isNotEmpty(birthDateBegin)">
				AND BIRTH_DATE >= #{birthDateBegin}
		   </if>
		   <if test="@Ognl@isNotEmpty(birthDateEnd)">
				AND BIRTH_DATE &lt;= #{birthDateEnd}
		   </if>
	       <if test="@Ognl@isNotEmpty(sex)">
				AND SEX = #{sex}
			</if>
	       <if test="@Ognl@isNotEmpty(age)">
				AND AGE = #{age}
			</if>
			<choose>
				<when test="@Ognl@isNotEmpty(sex)">AND sex = #{sexWhen}</when>
				<when test="@Ognl@isNotEmpty(sex)">AND age = #{ageWhen}</when>
				<otherwise>AND BIRTH_DATE = #{birthDateOtherwise}</otherwise>
			</choose>
			and username in 
			<foreach collection="usernamesByItem" item="item" index="index" open="(" separator="," close=")">  
        		#{item} 
   			</foreach> 
   			and username in 
   			<foreach collection="usernamesByIndexDollar" item="item" index="index" open="(" separator="," close=")">  
       		#{usernamesByIndex[${index}]}
  			</foreach> 	
  			
  			and username in 
   			<foreach collection="usernamesByIndex" item="item" index="index" open="(" separator="," close=")">  
       		#{usernamesByIndex[index]}
  			</foreach> 			
		</where>
	</sql>
		
	<!-- resultType="long" -->
    <operation name="UserInfo.findPage.count" >
    	<sql>
        SELECT count(*) FROM USER_INFO 
		<include refid="UserInfo.findPage.where"/>    
		</sql>
    </operation>
    
    <!--
    	分页查询已经使用Dialect进行分页,也可以不使用Dialect直接编写分页
    	因为分页查询将传 offset,pageSize,lastRows 三个参数,不同的数据库可以根于此三个参数属性应用不同的分页实现
    	
    	resultMap="RM.UserInfo"
    -->
    <operation name="UserInfo.findPage" >
    	<sql>
    	SELECT <include refid="UserInfo.columns" />
	    FROM USER_INFO 
		<include refid="UserInfo.findPage.where"/>
		
		<if test="@Ognl@isNotEmpty(sortColumns)">
			ORDER BY ${sortColumns}
		</if>
		</sql>
    </operation>
	
	<!-- resultMap="RM.UserInfo" parameterType="java.lang.String" -->
    <operation name="UserInfo.getByUsername" >
    	<sql>
	    SELECT <include refid="UserInfo.columns"/>
	    <![CDATA[
	        FROM USER_INFO where USERNAME = #{username}
	    ]]>
	    </sql>
    </operation>
    
    <!-- resultMap="RM.UserInfo" parameterType="java.lang.Integer" -->
    <operation name="UserInfo.getByAge" >
    	<sql>
	    SELECT <include refid="UserInfo.columns"/>
	    <![CDATA[
	        FROM USER_INFO where AGE = #{age}
	    ]]>
	    </sql>
    </operation>      			
</table>
